import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./providers";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});
const natasha = localFont({
  src: "../public/assets/fonts/Natasha-Walker.otf",
  variable: "--font-natasha",
});
const cochon = localFont({
  src: "../public/assets/fonts/Petit-Cochon.ttf",
  variable: "--font-cochon",
});

export const metadata: Metadata = {
  title: "Cookmate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${natasha.variable} ${cochon.variable} font-montserrat`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
